-- Travis: The Game — upgrade 13: a public activity feed. Every signed-in player can see, live, what
-- everyone else is doing — packs won and opened, and battles starting/finishing — each with an exact
-- timestamp. Paste into Supabase → SQL Editor → Run. Safe to run more than once.

create table if not exists public.activity (
  id         bigint generated by default as identity primary key,
  user_id    uuid references public.profiles(id) on delete cascade,
  username   text not null,
  kind       text not null check (kind in ('pack_won','wager_lost','pack_opened','game_start','game_end')),
  detail     jsonb not null default '{}',
  created_at timestamptz not null default now()
);
create index if not exists activity_created_at_idx on public.activity (created_at desc);
alter table public.activity enable row level security;
drop policy if exists "read activity" on public.activity;
create policy "read activity" on public.activity for select to authenticated using (true);
-- No insert/update/delete policy: rows only ever come from the security-definer functions below,
-- never directly from a client, so nobody can post a fake entry into someone else's feed.

-- Broadcast inserts over Realtime so the home screen updates live, with no polling.
do $$ begin
  alter publication supabase_realtime add table public.activity;
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------- record_win, with activity logging
create or replace function public.record_win() returns text
language plpgsql security definer set search_path = public as $$
declare today date := (now() at time zone 'Australia/Sydney')::date; p profiles;
        total int; roll int; won_pack text;
begin
  select * into p from profiles where id = auth.uid() for update;
  if not found then raise exception 'Not signed in'; end if;
  if p.wins_day is distinct from today then p.wins_today := 0; end if;
  if p.wins_today >= 5 then
    update profiles set wins_day = today, wins_today = p.wins_today where id = p.id;
    return null;
  end if;
  if random() < 1.0/3 then
    won_pack := case when random() < 0.5 then 'holo' else 'legendary' end;
    insert into pack_stock (user_id, pack_id, qty) values (p.id, won_pack, 1)
      on conflict (user_id, pack_id) do update set qty = pack_stock.qty + 1;
    update profiles set wins_day = today, wins_today = p.wins_today + 1 where id = p.id;
    insert into activity (user_id, username, kind, detail) values (p.id, p.username, 'pack_won', jsonb_build_object('pack', won_pack, 'source', 'win'));
    return won_pack;
  end if;
  select coalesce(sum(win_weight), 0) into total from packs
    where win_weight > 0 and active and (valid_until is null or now() <= valid_until);
  if total <= 0 then
    update profiles set packs = packs + 1, wins_day = today, wins_today = p.wins_today + 1 where id = p.id;
    insert into activity (user_id, username, kind, detail) values (p.id, p.username, 'pack_won', jsonb_build_object('pack', 'any', 'source', 'win'));
    return 'any';
  end if;
  roll := floor(random() * total)::int;
  select x.id into won_pack from (
    select id, sum(win_weight) over (order by id) as upto from packs
    where win_weight > 0 and active and (valid_until is null or now() <= valid_until)
  ) x where roll < x.upto order by x.upto limit 1;
  insert into pack_stock (user_id, pack_id, qty) values (p.id, won_pack, 1)
    on conflict (user_id, pack_id) do update set qty = pack_stock.qty + 1;
  update profiles set wins_day = today, wins_today = p.wins_today + 1 where id = p.id;
  insert into activity (user_id, username, kind, detail) values (p.id, p.username, 'pack_won', jsonb_build_object('pack', won_pack, 'source', 'win'));
  return won_pack;
end $$;

-- ---------------------------------------------------------------- open_pack, with activity logging
create or replace function public.open_pack(p_pack text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); uname text; result jsonb := '[]'; i int; total int; roll int; pick text;
        cid text; is_foil boolean; cap int; pts int; owned int; pk packs;
begin
  select username into uname from profiles where id = uid;
  select * into pk from packs where id = p_pack and active;
  if pk.id is null then raise exception 'That pack isn''t available'; end if;
  if pk.valid_until is not null and now() > pk.valid_until then raise exception '% is no longer available', pk.name; end if;
  select coalesce(sum(weight), 0) into total from pack_odds where pack_id = p_pack;
  if total <= 0 then raise exception 'That pack has no odds set'; end if;
  update pack_stock set qty = qty - 1 where user_id = uid and pack_id = p_pack and qty > 0;
  if not found then
    if not pk.open_with_any then raise exception '% can only be opened with a pack of that exact type', pk.name; end if;
    update profiles set packs = packs - 1 where id = uid and packs > 0;
    if not found then raise exception 'No packs to open'; end if;
  end if;
  for i in 1..3 loop
    roll := floor(random() * total)::int;
    select o.slot into pick from (
      select slot, sum(weight) over (order by case slot when 'starter' then 1 when 'common' then 2 when 'rare' then 3 else 4 end) as upto
      from pack_odds where pack_id = p_pack and weight > 0) o
    where roll < o.upto order by o.upto limit 1;
    cid := null; is_foil := false;
    if pick = 'common' then
      select id into cid from cards where pack_id = p_pack and rarity = 'common' order by random() limit 1; cap := 3; pts := 2;
    elsif pick = 'rare' then
      select id into cid from cards where pack_id = p_pack and rarity = 'rare' order by random() limit 1; cap := 1; pts := 5;
    elsif pick = 'foil' then
      select id into cid from cards where rarity = 'base' and kind = 'character' order by random() limit 1; is_foil := true; cap := 1; pts := 5;
    end if;
    if cid is null then
      select id into cid from cards where rarity = 'base' order by random() limit 1;
      update profiles set grant_points = grant_points + 1 where id = uid;
      result := result || jsonb_build_object('id', cid, 'foil', false, 'dupe', true, 'starter', true, 'points', 1);
      continue;
    end if;
    select coalesce(sum(qty), 0) into owned from collection where user_id = uid and card_id = cid and foil = is_foil;
    if owned >= cap then
      update profiles set grant_points = grant_points + pts where id = uid;
      result := result || jsonb_build_object('id', cid, 'foil', is_foil, 'dupe', true, 'starter', false, 'points', pts);
    else
      insert into collection (user_id, card_id, foil, qty) values (uid, cid, is_foil, 1)
        on conflict (user_id, card_id, foil) do update set qty = collection.qty + 1;
      result := result || jsonb_build_object('id', cid, 'foil', is_foil, 'dupe', false, 'starter', false, 'points', 0);
    end if;
  end loop;
  insert into activity (user_id, username, kind, detail) values (uid, uname, 'pack_opened', jsonb_build_object('pack', pk.name, 'cards', result));
  return result;
end $$;

-- ---------------------------------------------------------------- battle start/end activity
create function public.log_game_start(p_mode text, p_difficulty text, p_size int, p_opponent text) returns void
language plpgsql security definer set search_path = public as $$
declare uname text;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  select username into uname from profiles where id = auth.uid();
  insert into activity (user_id, username, kind, detail) values (auth.uid(), uname, 'game_start',
    jsonb_build_object('mode', p_mode, 'difficulty', p_difficulty, 'size', p_size, 'opponent', left(coalesce(p_opponent, 'CPU'), 30)));
end $$;

create or replace function public.log_game(p_mode text, p_difficulty text, p_size int, p_result text,
  p_rounds int, p_seconds int, p_opponent text, p_deck text) returns void
language plpgsql security definer set search_path = public as $$
declare v_xp int; uname text;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  select username into uname from profiles where id = auth.uid();
  v_xp := case when p_result = 'quit' then 0 else
    round((8 + case when p_result = 'win' then 12 else 0 end) *
      case when p_mode = 'online' then 1.2
           when p_difficulty = 'hard' then 1.4
           when p_difficulty = 'easy' then 0.75
           else 1 end)::int
  end;
  insert into games (user_id, mode, difficulty, size, result, rounds, seconds, opponent, deck_name, xp)
  values (auth.uid(), p_mode, case when p_mode = 'cpu' then p_difficulty end, p_size, p_result,
          least(greatest(coalesce(p_rounds, 0), 0), 999), least(greatest(coalesce(p_seconds, 0), 0), 86400),
          left(p_opponent, 30), left(p_deck, 30), v_xp);
  update profiles set last_seen = now(), xp = profiles.xp + v_xp where id = auth.uid();
  if p_result <> 'quit' then
    insert into activity (user_id, username, kind, detail) values (auth.uid(), uname, 'game_end',
      jsonb_build_object('mode', p_mode, 'difficulty', p_difficulty, 'size', p_size, 'result', p_result,
        'rounds', p_rounds, 'opponent', left(coalesce(p_opponent, 'CPU'), 30)));
  end if;
end $$;

-- ---------------------------------------------------------------- wager_battle, with activity logging
create or replace function public.wager_battle(p_stake int, p_won boolean, p_mode text, p_difficulty text)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); uname text; pts int; total int; roll int; won_pack text;
begin
  select username into uname from profiles where id = uid;
  if p_stake < 10 or p_stake > 100 then raise exception 'Stakes run 10 to 100 Grant Points.'; end if;
  if not (p_mode = 'online' or (p_mode = 'cpu' and p_difficulty = 'hard')) then
    raise exception 'High Stakes is only for Hard CPU or Online games.';
  end if;
  if not p_won then
    update profiles set grant_points = greatest(0, grant_points - p_stake) where id = uid
      returning grant_points into pts;
    if not found then raise exception 'Not signed in'; end if;
    insert into activity (user_id, username, kind, detail) values (uid, uname, 'wager_lost', jsonb_build_object('stake', p_stake));
    return jsonb_build_object('won', false, 'lost', p_stake, 'grant_points', pts);
  end if;
  if random() < 1.0/3 then
    won_pack := case when random() < 0.5 then 'holo' else 'legendary' end;
    insert into pack_stock (user_id, pack_id, qty) values (uid, won_pack, 1)
      on conflict (user_id, pack_id) do update set qty = pack_stock.qty + 1;
    insert into activity (user_id, username, kind, detail) values (uid, uname, 'pack_won', jsonb_build_object('pack', won_pack, 'source', 'wager'));
    return jsonb_build_object('won', true, 'pack', won_pack);
  end if;
  select coalesce(sum(win_weight), 0) into total from packs
    where win_weight > 0 and active and (valid_until is null or now() <= valid_until);
  if total <= 0 then
    update profiles set packs = packs + 1 where id = uid;
    insert into activity (user_id, username, kind, detail) values (uid, uname, 'pack_won', jsonb_build_object('pack', 'any', 'source', 'wager'));
    return jsonb_build_object('won', true, 'pack', 'any');
  end if;
  roll := floor(random() * total)::int;
  select x.id into won_pack from (
    select id, sum(win_weight) over (order by id) as upto from packs
    where win_weight > 0 and active and (valid_until is null or now() <= valid_until)
  ) x where roll < x.upto order by x.upto limit 1;
  insert into pack_stock (user_id, pack_id, qty) values (uid, won_pack, 1)
    on conflict (user_id, pack_id) do update set qty = pack_stock.qty + 1;
  insert into activity (user_id, username, kind, detail) values (uid, uname, 'pack_won', jsonb_build_object('pack', won_pack, 'source', 'wager'));
  return jsonb_build_object('won', true, 'pack', won_pack);
end $$;

revoke all on function public.log_game_start(text, text, int, text) from public, anon;
grant execute on function public.log_game_start(text, text, int, text) to authenticated;
grant select on public.activity to authenticated;
